### PR TITLE
feature - Add dark mode toggle

### PR DESCRIPTION
**Pull request by yashu183**
Added toggle btn to switch the theme but I feel we need to chnage the green color for light theme

### CODE REVIEW

**Comment by pavankalyan-codes** [comment]
> Added toggle btn to switch the theme but I feel we need to chnage the green color for light theme
Thanks for the contribution @yashu183 !!
As you said, we need more contrasted color for light theme. green we are using isn't looking good. Try using more darker green. Also, would you be able to movie toggle button below the title. Currently the toggle and the title are overlapping

**Comment by yashu183** [comment]
Sure!! 
Should I grp it with the stats, time travel and info btns?

**Comment by yashu183** [comment]
Updated the PR with mentioned changes

**Comment by pavankalyan-codes** [comment]
Here the icon is still overlapping with the title. Would you be able to fix that pls. Thanks

**Comment by pavankalyan-codes** [comment]
Also, not sure what does submit button would be used for. It adds one more extra step for the user.

**Comment by yashu183** [comment]
Sure will fix that positioning issue

Regarding the submit btn : 
As I mentioned in #96 we can get rid of accidental tap. If I want to select the first suggestion in the drop down and I accidently tapped second suggestion its submitting...so unnecessarly users lose their guess so If we have submit btn then they can review it and submit again

I will seperate these two PRs and will raise a new PR for theme toggle

**Comment by pavankalyan-codes** [comment]
Yeah, separate the PRs. Theme toggle looks fine. Will merge that. We can discuss regarding the submit button UX in a separate PR.

**Comment by yashu183** [comment]
Raised another PR for theme toggling

**Pull request closed without merging**
