### PR TITLE
Added theme toggle feature

### PR DESCRIPTION
**Pull request by yashu183**
Removed submit btn changes
sry I forgot to change the positioning in time travel page in the prev PR, over looked it

### CODE REVIEW

**Comment by pavankalyan-codes** [comment]
@yashu183 would like to walk thru PR, are you on discord ?

**Comment by yashu183** [comment]
yeah
ABD_17 is the username

**Comment by pavankalyan-codes** [comment]
> yeah ABD_17 is the username

Couldn't invite, join here https://discord.gg/e6cEzKF7

**Comment by pavankalyan-codes** [comment]
@yashu183 could you pls resolve conflicts? Will merge this.

**Comment by yashu183** [comment]
@pavankalyan-codes Done

**Pull request merged**
