### PR TITLE
storing attempts in local storage to show guess distribution

### PR DESCRIPTION
**Pull request by pavankalyan-codes**

### CODE REVIEW

**Comment by santoshimz** [comment]
So this will store number of attempts daily as a CSV ?

So on day 1 if I have 3 attempts, day 2 if i have 4 attempts -> you will store 3,4 ? 

How do you plan to use it ?

**Comment by pavankalyan-codes** [comment]
In the stats modal, will be using this data to show average attempts taken to guess the answer. 
Refer the below image

**Comment by pavankalyan-codes** [comment]
I think it would be better to use some data structure like js object to store this data rather than CSV. let me update the PR for the same. @santoshimz

**Comment by santoshimz** [comment]
Are the changes for StatsModal in this PR?

**Comment by pavankalyan-codes** [comment]
> Are the changes for StatsModal in this PR?

No, I am yet to make that change. I made this initial commit so we don't miss any past data of users until we make that UI change.

**Comment by santoshimz** [comment]
Lgtm

**Pull request merged**
